import { Metadata } from "next";
const metadata: Metadata = {
    title: {
      template: "s/ PsycoTena",
      default: "Welcome to TenaPsyco",
    },
    description: "Generated by create next app",
  };
